#spring.application.name=springjpa
spring:
  application:
    name: springjpa
  datasource:
    url: localhost
    username: root
    password: 5168
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update